# These are supported funding model platforms

github: ut0s
patreon: ut0s
open_collective:
ko_fi: ut0s_dev
tidelift: # Replace with a single Tidelift platform-name/package-name e.g., npm/babel
community_bridge: # Replace with a single Community Bridge project-name e.g., cloud-foundry
liberapay: # Replace with a single Liberapay username
issuehunt:
otechie: # Replace with a single Otechie username
custom: # Replace with a single custom sponsorship URL
