/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    BuyMeACoffee: typeof import('./components/BuyMeACoffee.vue')['default']
    CheckBox: typeof import('./components/CheckBox.vue')['default']
    FeatureRequestBugReport: typeof import('./components/FeatureRequestBugReport.vue')['default']
    GithubSponsor: typeof import('./components/GithubSponsor.vue')['default']
    Kofi: typeof import('./components/Kofi.vue')['default']
    ModalAboutAccuracyOption: typeof import('./components/ModalAboutAccuracyOption.vue')['default']
    ModalAboutWildcardsOption: typeof import('./components/ModalAboutWildcardsOption.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
